namespace HawkN.Iso.Currencies.Generators.Tests;

public class BaseIncrementalGeneratorTests
{
    [Fact]
    public void CreateSourceBuilder_ShouldContainStandardHeaderAndNamespace()
    {
        // Arrange
        const string generatorName = "BaseIncrementalGenerator";
        const string expectedNamespace = "TestNamespace";

        // Act
        var sb = BaseIncrementalGenerator.CreateSourceBuilder(generatorName, expectedNamespace, []);
        var result = sb.ToString();

        // Assert
        Assert.Contains("// <auto-generated>", result);
        Assert.Contains($"//     This file was generated by {generatorName}", result);
        Assert.Contains($"namespace {expectedNamespace}", result);
        Assert.Contains("#nullable enable", result);
        Assert.Contains("{", result);
    }

    [Fact]
    public void CreateSourceBuilder_ShouldIncludeReferencesWhenProvided()
    {
        // Arrange
        var references = new[] { "System", "System.Collections.Generic" };

        // Act
        var sb = BaseIncrementalGenerator.CreateSourceBuilder("Gen", "Ns", [], references);
        var result = sb.ToString();

        // Assert
        Assert.Contains("using System;", result);
        Assert.Contains("using System.Collections.Generic;", result);
    }

    [Fact]
    public void CreateSourceBuilder_ShouldNotIncludeReferencesWhenNull()
    {
        // Act
        var sb = BaseIncrementalGenerator.CreateSourceBuilder("Gen", "Ns", [], null);
        var result = sb.ToString();

        // Assert
        Assert.DoesNotContain("using", result);
    }
}

