using System.Reflection;
using System.Text;
using HawkN.Iso.Currencies.Generators.Factories;
using HawkN.Iso.Currencies.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace HawkN.Iso.Currencies.Generators;

public abstract class BaseIncrementalGenerator : IIncrementalGenerator
{
    protected virtual string HintName { get; } = string.Empty;
    protected readonly ErrorFactory ErrorFactory = new();
    public abstract void Initialize(IncrementalGeneratorInitializationContext context);

    protected void AddStubIfErrors(SourceProductionContext spc, string hintName, string stubSource, GeneratorType type)
    {
        if (!ErrorFactory.IsExists()) return;
        ErrorFactory.ShowDiagnostics(spc, type);
        spc.AddSource(hintName, SourceText.From(stubSource, Encoding.UTF8));
    }

    protected static (string original, string replacement, string historical) LoadJsonResources(Assembly assembly)
    {
        string ReadResource(string name)
        {
            using var stream = assembly.GetManifestResourceStream(name)
                               ?? throw new InvalidOperationException($"{name} not found.");
            using var reader = new StreamReader(stream, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return reader.ReadToEnd();
        }

        return (
            ReadResource("HawkN.Iso.Currencies.Generators.Content.list-original-currencies.json"),
            ReadResource("HawkN.Iso.Currencies.Generators.Content.list-replacement-currency-names.json"),
            ReadResource("HawkN.Iso.Currencies.Generators.Content.list-historical-currencies.json")
        );
    }

    protected void GenerateSourceOutput((string, string, string) tuple, SourceProductionContext spc)
    {
        ErrorFactory.Create(new ErrorDescription
        {
            DiagnosticDescriptor = new DiagnosticDescriptor(
                id: DiagnosticDescriptors.UnexpectedErrorId,
                title: Constants.DiagnosticsTitle,
                messageFormat: "Unexpected exception: Unexpected error",
                category: string.Empty,
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true),
            GeneratorType = GeneratorType.Factory
        });
        ErrorFactory.ShowDiagnostics(spc, GeneratorType.Factory);
    }

    internal static StringBuilder CreateSourceBuilder(string generatorName, string @namespace, string[]? references = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"//     This file was generated by {generatorName}");
        sb.AppendLine("//     Do not modify this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        if (references is not null && references.Any())
        {
            foreach (var referenceName in references)
                sb.AppendLine($"using {referenceName};");
        }
        sb.AppendLine($"namespace {@namespace}");
        sb.AppendLine("{");
        return sb;
    }
}