using System.Reflection;
using System.Text;
using HawkN.Iso.Currencies.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace HawkN.Iso.Currencies.Generators;

[Generator]
public class CurrencyCodeGenerator : BaseIncrementalGenerator
{
    protected override string HintName => "CurrencyCode.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //    This file was generated by HawkN.Iso.Currencies.Generators source generator.
                                      //    Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      namespace HawkN.Iso.Currencies
                                      {
                                          /// <summary> Currency codes ISO4217 </summary>
                                          public enum CurrencyCode
                                          {
                                              /// <summary> Unknown currency code </summary>
                                              None,
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();
        var jsonProvider = context.CompilationProvider.Select(ReadDataResource);
        context.RegisterSourceOutput(jsonProvider, (spc, tuple) => GenerateSourceOutput(tuple, spc));
    }

    static (string, string, string, string) ReadDataResource(Compilation compilation, CancellationToken ct)
    {
        try
        {
            return LoadResources(Assembly.GetExecutingAssembly());
        }
        catch (InvalidOperationException ex)
        {
            var errorMsg = $"{Constants.ErrorMark}:{ex.Message}";
            return (errorMsg, errorMsg, errorMsg, errorMsg);
        }
    }

    private void GenerateSourceOutput((string, string, string, string) tuple, SourceProductionContext spc)
    {
        try
        {
            var (originalXml, translationsXml, replacementJson, currencyCodesCsv) = tuple;

            if (HasResourceErrors(originalXml, translationsXml, replacementJson, currencyCodesCsv))
            {
                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
                return;
            }

            var loader = new CurrencyDataLoader(originalXml, translationsXml, replacementJson, currencyCodesCsv);
            var sb = CreateSourceBuilder(
                Constants.GeneratorName,
                Constants.DefaultNamespace,
                Constants.ExtendedSourceData
            );

            if (string.IsNullOrEmpty(loader.ActualCurrencyData.PublishedDate))
            {
                sb.AppendLine("    /// <summary> Currency codes ISO4217 </summary>");
            }
            else
            {
                sb.AppendLine("    /// <summary>")
                    .AppendLine("    /// Currency codes ISO4217")
                    .AppendLine($"    /// Last published at {loader.ActualCurrencyData.PublishedDate}.")
                    .AppendLine("    /// </summary>");
            }

            sb.AppendLine("    public enum CurrencyCode")
                .AppendLine("    {")
                .AppendLine("        /// <summary> Unknown currency code </summary>")
                .AppendLine("        None,");

            foreach (var c in loader.ActualCurrencyData.Currencies)
            {
                sb.AppendLine($"        /// <summary> {c.Name} </summary>");
                sb.AppendLine($"        {c.Code},");
            }

            sb.AppendLine("    }")
                .AppendLine("}");

            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    id: CreateDescriptorId("0"),
                    title: Constants.DiagnosticsTitle,
                    messageFormat: $"Unexpected exception: {ex.Message}",
                    category: string.Empty,
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                GeneratorType = GeneratorType.Currency
            });

            AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
        }
    }

    private bool HasResourceErrors(string originalXml, string translationsXml, string replacementJson, string currencyCodesCsv)
    {
        var hasError = false;

        void ReportError(string message, GeneratorType type)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    id: CreateDescriptorId("1"),
                    title: Constants.DiagnosticsTitle,
                    messageFormat: message,
                    category: string.Empty,
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                GeneratorType = type
            });
        }

        if (originalXml.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load original resource: {originalXml.Substring(8)}", GeneratorType.Currency);
            hasError = true;
        }
        if (replacementJson.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load replacement resource: {replacementJson.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }
        if (translationsXml.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load translations resource: {translationsXml.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }
        if (currencyCodesCsv.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load currency codes resource: {currencyCodesCsv.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }

        return hasError;
    }
}