using System.Reflection;
using System.Text;
using HawkN.Iso.Currencies.Generators.Handlers;
using HawkN.Iso.Currencies.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
namespace HawkN.Iso.Currencies.Generators;

[Generator]
public class CurrencyCodeGenerator : BaseIncrementalGenerator
{
    protected override string HintName => "CurrencyCode.g.cs";

    private const string StubSource = """
                                      // <auto-generated>
                                      //    This file was generated by HawkN.Iso.Currencies.Generators source generator.
                                      //    Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      namespace HawkN.Iso.Currencies
                                      {
                                          /// <summary> Currency codes ISO4217 </summary>
                                          public enum CurrencyCode
                                          {
                                              /// <summary> Unknown currency code </summary>
                                              None,
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();

        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                return LoadJsonResources(Assembly.GetExecutingAssembly());
            }
            catch (Exception ex)
            {
                var message = $"{Constants.ErrorMark}:{ex.Message}";
                return (message, message, message);
            }
        });

        context.RegisterSourceOutput(jsonProvider, (spc, tuple) => GenerateSourceOutput(tuple, spc));
    }

    private new void GenerateSourceOutput((string, string, string) tuple, SourceProductionContext spc)
    {
        try
        {
            var (originalJson, replacementJson, historicalJson) = tuple;

            if (HasResourceErrors(originalJson, replacementJson, historicalJson))
            {
                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
                return;
            }

            var loader = new CurrencyLoader(originalJson, replacementJson, historicalJson);
            var sb = CreateSourceBuilder(
                Constants.GeneratorName,
                Constants.DefaultNamespace
            );

            if (string.IsNullOrEmpty(loader.ActualCurrencyData.PublishedDate))
            {
                sb.AppendLine("    /// <summary> Currency codes ISO4217 </summary>");
            }
            else
            {
                sb.AppendLine("    /// <summary>")
                  .AppendLine("    /// Currency codes ISO4217")
                  .AppendLine($"    /// Last published at {loader.ActualCurrencyData.PublishedDate}.")
                  .AppendLine("    /// </summary>");
            }

            sb.AppendLine("    public enum CurrencyCode")
              .AppendLine("    {")
              .AppendLine("        /// <summary> Unknown currency code </summary>")
              .AppendLine("        None,");

            foreach (var c in loader.ActualCurrencyData.Currencies)
            {
                sb.AppendLine($"        /// <summary> {c.Name} </summary>");
                if (c.IsHistoric && !string.IsNullOrEmpty(c.WithdrawalDate))
                    sb.AppendLine($"        [Obsolete(\"Currency withdrawn on {c.WithdrawalDate}\")]");

                sb.AppendLine($"        {c.Code},");
            }

            sb.AppendLine("    }")
              .AppendLine("}");

            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    id: DiagnosticDescriptors.UnexpectedErrorId,
                    title: Constants.DiagnosticsTitle,
                    messageFormat: $"Unexpected exception: {ex.Message}",
                    category: string.Empty,
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                GeneratorType = GeneratorType.Currency
            });

            AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Currency);
        }
    }

    private bool HasResourceErrors(string originalJson, string replacementJson, string historicalJson)
    {
        var hasError = false;

        void ReportError(string message, GeneratorType type)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    id: DiagnosticDescriptors.ResourceLoadErrorId,
                    title: Constants.DiagnosticsTitle,
                    messageFormat: message,
                    category: string.Empty,
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                GeneratorType = type
            });
        }

        if (originalJson.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load original resource: {originalJson.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }
        if (replacementJson.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load replacement resource: {replacementJson.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }
        if (historicalJson.StartsWith(Constants.ErrorMark, StringComparison.Ordinal))
        {
            ReportError($"Failed to load historical resource: {historicalJson.Substring(9)}", GeneratorType.Currency);
            hasError = true;
        }

        return hasError;
    }
}