using System.Globalization;
using System.Reflection;
using System.Text;
using HawkN.Iso.Currencies.Generators.Handlers;
using HawkN.Iso.Currencies.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HawkN.Iso.Currencies.Generators;

[Generator]
public class LocalCurrencyDatabaseGenerator : BaseIncrementalGenerator
{
    protected override string HintName => "LocalCurrencyDatabase.g.cs";
    private const string StubSource = """
                                      // <auto-generated>
                                      //     This file was generated by HawkN.Iso.Currencies.Generators source generator.
                                      //     Do not modify this file manually.
                                      // </auto-generated>
                                      #nullable enable
                                      using System.Collections.Generic;
                                      using HawkN.Iso.Currencies.Models;
                                      namespace HawkN.Iso.Currencies
                                      {
                                          /// <summary> Currency information for codes ISO4217 </summary>
                                          internal static class LocalCurrencyDatabase
                                          {
                                              /// <summary> Actual currency information for codes ISO4217 </summary>
                                              public static readonly ImmutableArray<Models.Currency> ActualCurrencies = ImmutableArray.Create(
                                                new Models.Currency[]{});
                                              
                                              /// <summary> Currency historical information for codes ISO4217 </summary>
                                              public static readonly ImmutableArray<Models.Currency> HistoricalCurrencies= ImmutableArray.Create(
                                                new Models.Currency[]{});
                                          }
                                      }
                                      """;

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        ErrorFactory.Clear();
        var jsonProvider = context.CompilationProvider.Select((_, _) =>
        {
            try
            {
                return LoadJsonResources(Assembly.GetExecutingAssembly());
            }
            catch (Exception ex)
            {
                var errorMsg = $"{Constants.ErrorMark}:{ex.Message}";
                return (errorMsg, errorMsg, errorMsg);
            }
        });
        context.RegisterSourceOutput(jsonProvider, (spc, tuple) => GenerateSourceOutput(tuple, spc));
    }

    private new void GenerateSourceOutput((string originalJson, string replacementJson, string historicalJson) tuple,
        SourceProductionContext spc)
    {
        try
        {
            if (HasResourceErrors(tuple, out var errorMessages))
            {
                foreach (var msg in errorMessages)
                    ReportResourceError(msg);

                AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
                return;
            }

            var loader = new CurrencyLoader(tuple.originalJson, tuple.replacementJson, tuple.historicalJson);
            var sb = CreateSourceBuilder(Constants.GeneratorName, Constants.DefaultNamespace,
            [
                "System.Collections.Generic",
                "System.Collections.Immutable",
                "HawkN.Iso.Currencies.Models"
            ]);

            sb.AppendLine("    /// <summary> Currency information for codes ISO4217 </summary>")
                .AppendLine("    internal static class LocalCurrencyDatabase")
                .AppendLine("    {");

            GenerateCurrencySection(sb, "ActualCurrencies", loader.ActualCurrencyData);
            GenerateCurrencySection(sb, "HistoricalCurrencies", loader.HistoricalCurrencyData, isHistorical: true);

            sb.AppendLine("    }").AppendLine("}");
            spc.AddSource(HintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            ErrorFactory.Create(new ErrorDescription
            {
                DiagnosticDescriptor = new DiagnosticDescriptor(
                    DiagnosticDescriptors.UnexpectedErrorId,
                    Constants.DiagnosticsTitle,
                    $"Unexpected exception: {ex.Message}",
                    string.Empty,
                    DiagnosticSeverity.Error,
                    true),
                GeneratorType = GeneratorType.Database
            });
            AddStubIfErrors(spc, HintName, StubSource, GeneratorType.Database);
        }
    }

    private static bool HasResourceErrors((string originalJson, string replacementJson, string historicalJson) tuple,
        out List<string> messages)
    {
        messages = [];
        if (tuple.originalJson.StartsWith(Constants.ErrorMark)) messages.Add("original:" + tuple.originalJson);
        if (tuple.replacementJson.StartsWith(Constants.ErrorMark)) messages.Add("replacement:" + tuple.replacementJson);
        if (tuple.historicalJson.StartsWith(Constants.ErrorMark)) messages.Add("historical:" + tuple.historicalJson);
        return messages.Count > 0;
    }

    private static void GenerateCurrencySection(StringBuilder sb, string propertyName, CurrencyData data,
        bool isHistorical = false)
    {
        sb.AppendLine("        /// <summary>")
            .AppendLine(
                $"        /// {(isHistorical ? "Currency historical" : "Actual currency")} information for codes ISO4217");
        if (!string.IsNullOrEmpty(data.PublishedDate))
            sb.AppendLine($"        /// Last published at {data.PublishedDate}.");
        sb.AppendLine("        /// </summary>");

        sb.AppendLine(
                $"        public static readonly ImmutableArray<Models.Currency> {propertyName} = ImmutableArray.Create(new Models.Currency[]")
            .AppendLine("        {");
        foreach (var c in data.Currencies)
        {
            var currencyType = !c.IsHistoric && c.CurrencyType != null
                ? $"CurrencyType.{c.CurrencyType}"
                : "null";
            var isHist = c.IsHistoric ? "true" : "false";
            var withdrawal = ParseWithdrawalDate(c.WithdrawalDate!);
            sb.AppendLine(
                $"            new(\"{c.Code}\", \"{c.Name}\", \"{c.Country}\", \"{c.NumericCode}\", {isHist}, {withdrawal}, {currencyType}),");
        }

        sb.AppendLine("        });");
    }

    private static string ParseWithdrawalDate(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return "null";
        return DateTime.TryParseExact(raw, "yyyy-MM", CultureInfo.InvariantCulture, DateTimeStyles.None, out var dt)
            ? $"new DateOnly({dt.Year}, {dt.Month}, 1)"
            : "null";
    }

    private void ReportResourceError(string msg)
    {
        var parts = msg.Split([':'], 2);
        var name = parts[0];
        var text = parts.Length > 1 ? parts[1] : "Unknown error";

        ErrorFactory.Create(new ErrorDescription
        {
            DiagnosticDescriptor = new DiagnosticDescriptor(
                DiagnosticDescriptors.ResourceLoadErrorId,
                Constants.DiagnosticsTitle,
                $"Failed to load {name} resource: {text}",
                string.Empty,
                DiagnosticSeverity.Error,
                true),
            GeneratorType = GeneratorType.Database
        });
    }
}