// <auto-generated>
//     This file was generated by HawkN.Iso.Currencies.Generators source generator
//     Release: release-48.1.0
//     CLDR URL: https://github.com/unicode-org/cldr
//     Currency codes URL: https://raw.githubusercontent.com/datasets/currency-codes/main/data/codes-all.csv
//     Do not modify this file manually.
// </auto-generated>
#nullable enable
namespace HawkN.Iso.Currencies
{
    /// <summary>
    /// Currency codes ISO4217
    /// Last published at 2026-01-16.
    /// </summary>
    public enum CurrencyCode
    {
        /// <summary> Unknown currency code </summary>
        None,
        /// <summary> UAE Dirham </summary>
        AED,
        /// <summary> Afghani </summary>
        AFN,
        /// <summary> Albanian Lek </summary>
        ALL,
        /// <summary> Armenian Dram </summary>
        AMD,
        /// <summary> Angolan Kwanza </summary>
        AOA,
        /// <summary> Argentine Peso </summary>
        ARS,
        /// <summary> Australian Dollar </summary>
        AUD,
        /// <summary> Aruban Florin </summary>
        AWG,
        /// <summary> Azerbaijan Manat </summary>
        AZN,
        /// <summary> Convertible Mark </summary>
        BAM,
        /// <summary> Barbados Dollar </summary>
        BBD,
        /// <summary> Bangladeshi Taka </summary>
        BDT,
        /// <summary> Bahraini Dinar </summary>
        BHD,
        /// <summary> Burundian Franc </summary>
        BIF,
        /// <summary> Bermudian Dollar </summary>
        BMD,
        /// <summary> Brunei Dollar </summary>
        BND,
        /// <summary> Bolivian Boliviano </summary>
        BOB,
        /// <summary> Bolivian Mvdol </summary>
        BOV,
        /// <summary> Brazilian Real </summary>
        BRL,
        /// <summary> Bahamian Dollar </summary>
        BSD,
        /// <summary> Bhutanese Ngultrum </summary>
        BTN,
        /// <summary> Botswana Pula </summary>
        BWP,
        /// <summary> Belarusian Ruble </summary>
        BYN,
        /// <summary> Belize Dollar </summary>
        BZD,
        /// <summary> Canadian Dollar </summary>
        CAD,
        /// <summary> Congolese Franc </summary>
        CDF,
        /// <summary> WIR Euro </summary>
        CHE,
        /// <summary> Swiss Franc </summary>
        CHF,
        /// <summary> WIR Franc </summary>
        CHW,
        /// <summary> Unidad de Fomento </summary>
        CLF,
        /// <summary> Chilean Peso </summary>
        CLP,
        /// <summary> Chinese Yuan </summary>
        CNY,
        /// <summary> Colombian Peso </summary>
        COP,
        /// <summary> Unidad de Valor Real </summary>
        COU,
        /// <summary> Costa Rican Colón </summary>
        CRC,
        /// <summary> Cuban Peso </summary>
        CUP,
        /// <summary> Cape Verde Escudo </summary>
        CVE,
        /// <summary> Czech Koruna </summary>
        CZK,
        /// <summary> Djiboutian Franc </summary>
        DJF,
        /// <summary> Danish Krone </summary>
        DKK,
        /// <summary> Dominican Peso </summary>
        DOP,
        /// <summary> Algerian Dinar </summary>
        DZD,
        /// <summary> Egyptian Pound </summary>
        EGP,
        /// <summary> Eritrean Nakfa </summary>
        ERN,
        /// <summary> Ethiopian Birr </summary>
        ETB,
        /// <summary> Euro </summary>
        EUR,
        /// <summary> Fiji Dollar </summary>
        FJD,
        /// <summary> Falkland Islands Pound </summary>
        FKP,
        /// <summary> British Pound </summary>
        GBP,
        /// <summary> Georgian Lari </summary>
        GEL,
        /// <summary> Ghanaian Cedi </summary>
        GHS,
        /// <summary> Gibraltar Pound </summary>
        GIP,
        /// <summary> Gambian Dalasi </summary>
        GMD,
        /// <summary> Guinean Franc </summary>
        GNF,
        /// <summary> Guatemalan Quetzal </summary>
        GTQ,
        /// <summary> Guyanese Dollar </summary>
        GYD,
        /// <summary> Hong Kong Dollar </summary>
        HKD,
        /// <summary> Honduran Lempira </summary>
        HNL,
        /// <summary> Haitian Gourde </summary>
        HTG,
        /// <summary> Hungarian Forint </summary>
        HUF,
        /// <summary> Indonesian Rupiah </summary>
        IDR,
        /// <summary> Israeli New Shekel </summary>
        ILS,
        /// <summary> Indian Rupee </summary>
        INR,
        /// <summary> Iraqi Dinar </summary>
        IQD,
        /// <summary> Iranian Rial </summary>
        IRR,
        /// <summary> Icelandic Krona </summary>
        ISK,
        /// <summary> Jamaican Dollar </summary>
        JMD,
        /// <summary> Jordanian Dinar </summary>
        JOD,
        /// <summary> Japanese Yen </summary>
        JPY,
        /// <summary> Kenyan Shilling </summary>
        KES,
        /// <summary> Kyrgyzstani Som </summary>
        KGS,
        /// <summary> Cambodian Riel </summary>
        KHR,
        /// <summary> Comorian Franc </summary>
        KMF,
        /// <summary> North Korean Won </summary>
        KPW,
        /// <summary> South Korean Won </summary>
        KRW,
        /// <summary> Kuwaiti Dinar </summary>
        KWD,
        /// <summary> Cayman Islands Dollar </summary>
        KYD,
        /// <summary> Kazakhstani Tenge </summary>
        KZT,
        /// <summary> Lao Kip </summary>
        LAK,
        /// <summary> Lebanese Pound </summary>
        LBP,
        /// <summary> Sri Lankan Rupee </summary>
        LKR,
        /// <summary> Liberian Dollar </summary>
        LRD,
        /// <summary> Lesotho Loti </summary>
        LSL,
        /// <summary> Libyan Dinar </summary>
        LYD,
        /// <summary> Moroccan Dirham </summary>
        MAD,
        /// <summary> Moldovan Leu </summary>
        MDL,
        /// <summary> Malagasy Ariary </summary>
        MGA,
        /// <summary> Macedonian Denar </summary>
        MKD,
        /// <summary> Myanmar Kyat </summary>
        MMK,
        /// <summary> Mongolian Tugrik </summary>
        MNT,
        /// <summary> Macanese Pataca </summary>
        MOP,
        /// <summary> Mauritanian Ouguiya </summary>
        MRU,
        /// <summary> Mauritian Rupee </summary>
        MUR,
        /// <summary> Maldivian Rufiyaa </summary>
        MVR,
        /// <summary> Malawian Kwacha </summary>
        MWK,
        /// <summary> Mexican Peso </summary>
        MXN,
        /// <summary> Mexican Investment Unit </summary>
        MXV,
        /// <summary> Malaysian Ringgit </summary>
        MYR,
        /// <summary> Mozambican Metical </summary>
        MZN,
        /// <summary> Namibian Dollar </summary>
        NAD,
        /// <summary> Nigerian Naira </summary>
        NGN,
        /// <summary> Nicaraguan Córdoba </summary>
        NIO,
        /// <summary> Norwegian Krone </summary>
        NOK,
        /// <summary> Nepalese Rupee </summary>
        NPR,
        /// <summary> New Zealand Dollar </summary>
        NZD,
        /// <summary> Omani Rial </summary>
        OMR,
        /// <summary> Panamanian Balboa </summary>
        PAB,
        /// <summary> Peruvian Sol </summary>
        PEN,
        /// <summary> Papua New Guinean Kina </summary>
        PGK,
        /// <summary> Philippine Peso </summary>
        PHP,
        /// <summary> Pakistani Rupee </summary>
        PKR,
        /// <summary> Polish Zloty </summary>
        PLN,
        /// <summary> Paraguayan Guarani </summary>
        PYG,
        /// <summary> Qatari Riyal </summary>
        QAR,
        /// <summary> Romanian Leu </summary>
        RON,
        /// <summary> Serbian Dinar </summary>
        RSD,
        /// <summary> Russian Ruble </summary>
        RUB,
        /// <summary> Rwandan Franc </summary>
        RWF,
        /// <summary> Saudi Riyal </summary>
        SAR,
        /// <summary> Solomon Islands Dollar </summary>
        SBD,
        /// <summary> Seychelles Rupee </summary>
        SCR,
        /// <summary> Sudanese Pound </summary>
        SDG,
        /// <summary> Swedish Krona </summary>
        SEK,
        /// <summary> Singapore Dollar </summary>
        SGD,
        /// <summary> Saint Helena Pound </summary>
        SHP,
        /// <summary> Sierra Leonean Leone </summary>
        SLE,
        /// <summary> Somali Shilling </summary>
        SOS,
        /// <summary> Surinamese Dollar </summary>
        SRD,
        /// <summary> South Sudanese Pound </summary>
        SSP,
        /// <summary> São Tomé and Príncipe Dobra </summary>
        STN,
        /// <summary> Syrian Pound </summary>
        SYP,
        /// <summary> Swazi Lilangeni </summary>
        SZL,
        /// <summary> Thai Baht </summary>
        THB,
        /// <summary> Tajikistani Somoni </summary>
        TJS,
        /// <summary> Turkmenistani Manat </summary>
        TMT,
        /// <summary> Tunisian Dinar </summary>
        TND,
        /// <summary> Tongan Paʻanga </summary>
        TOP,
        /// <summary> Turkish Lira </summary>
        TRY,
        /// <summary> Trinidad and Tobago Dollar </summary>
        TTD,
        /// <summary> New Taiwan Dollar </summary>
        TWD,
        /// <summary> Tanzanian Shilling </summary>
        TZS,
        /// <summary> Ukrainian Hryvnia </summary>
        UAH,
        /// <summary> Ugandan Shilling </summary>
        UGX,
        /// <summary> US Dollar </summary>
        USD,
        /// <summary> US Dollar (Next day) </summary>
        USN,
        /// <summary> Uruguayan Peso (Indexed Units) </summary>
        UYI,
        /// <summary> Uruguayan Peso </summary>
        UYU,
        /// <summary> Unidad Previsional </summary>
        UYW,
        /// <summary> Uzbekistani Som </summary>
        UZS,
        /// <summary> Venezuelan Bolívar </summary>
        VES,
        /// <summary> Vietnamese Dong </summary>
        VND,
        /// <summary> Vanuatu Vatu </summary>
        VUV,
        /// <summary> Samoan Tala </summary>
        WST,
        /// <summary> Central African CFA Franc </summary>
        XAF,
        /// <summary> Silver (one troy ounce) </summary>
        XAG,
        /// <summary> Gold (one troy ounce) </summary>
        XAU,
        /// <summary> European Composite Unit </summary>
        XBA,
        /// <summary> European Monetary Unit </summary>
        XBB,
        /// <summary> European Unit of Account (XBC) </summary>
        XBC,
        /// <summary> European Unit of Account (XBD) </summary>
        XBD,
        /// <summary> East Caribbean Dollar </summary>
        XCD,
        /// <summary> Special Drawing Rights </summary>
        XDR,
        /// <summary> West African CFA Franc </summary>
        XOF,
        /// <summary> Palladium (one troy ounce) </summary>
        XPD,
        /// <summary> CFP Franc </summary>
        XPF,
        /// <summary> Platinum (one troy ounce) </summary>
        XPT,
        /// <summary> Sucre (Unidad de Cuenta del ALBA) </summary>
        XSU,
        /// <summary> Testing Currency Code </summary>
        XTS,
        /// <summary> ADB Unit of Account </summary>
        XUA,
        /// <summary> Unknown Currency </summary>
        XXX,
        /// <summary> Yemeni Rial </summary>
        YER,
        /// <summary> South African Rand </summary>
        ZAR,
        /// <summary> Zambian Kwacha </summary>
        ZMW,
    }
}
